name: shared
description: "Shared module"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

# Modules
core:
  path: ../core

dependencies:
  flutter:
    sdk: flutter
  
  # Dependeny Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.3
  injectable_generator: ^2.6.2