name: snapix
description: "A photo gallery project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  
dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4

  # Routing
  go_router: ^14.6.3
  
  # Modules
  core:
    path: modules/core
  shared:
    path: modules/shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.3
  injectable_generator: ^2.6.2
  
flutter:
  uses-material-design: true