name: core
description: "Core funtionalities module"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Media
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

  # Routing
  go_router: ^14.6.3
  
  # Internationalization
  flutter_localizations:
    sdk: flutter

  # Utilities
  intl: ^0.19.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.8.0

flutter:
  generate: true