name: gallery
description: "Gallery module"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Code Generator
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  # Modules
  core:
    path: ../../core
  shared:
    path: ../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.3
  injectable_generator: ^2.6.2